INSERT INTO driver (driverFName, driverLName) VALUES ('Carl', 'Ragunton');
INSERT INTO driver (driverFName, driverLName) VALUES ('Wally', 'Bayola');
INSERT INTO driver (driverFName, driverLName) VALUES ('Vic', 'Sotto');
INSERT INTO driver (driverFName, driverLName) VALUES ('Erick', 'Sarenas');
INSERT INTO driver (driverFName, driverLName) VALUES ('Jose', 'Manalo');
INSERT INTO route (name, color, path) VALUES ('Ikot', 10, '( ( 10 , 20 ) , ( 30 , 40 ) )');
INSERT INTO route (name, color, path) VALUES ('Toki', 20, '( ( 10 , 20 ) , ( 30 , 40 ) )');
INSERT INTO route (name, color, path) VALUES ('Philcoa', 30, '( ( 10 , 20 ) , ( 30 , 40 ) )');
INSERT INTO route (name, color, path) VALUES ('Pantranco', 40, '( ( 10 , 20 ) , ( 30 , 40 ) )');
INSERT INTO route (name, color, path) VALUES ('Katipunan', 50, '( ( 10 , 20 ) , ( 30 , 40 ) )');
INSERT INTO tracker (coords) VALUES ('(45.2, 89.1)');
INSERT INTO tracker (coords) VALUES ('(13.2, 83.5)');
INSERT INTO tracker (coords) VALUES ('(342.2, 23.1)');
INSERT INTO tracker (coords) VALUES ('(2.2, 8432.3)');
INSERT INTO tracker (coords) VALUES ('(43.2, 634.1)');
INSERT INTO jeepney (trackerID, routeID, driverID, plateNumber, capacity) VALUES (1, 1, 1, 'PLT001', 8);
INSERT INTO jeepney (trackerID, routeID, driverID, plateNumber, capacity) VALUES (2, 2, 2, 'PLT002', 8);
INSERT INTO jeepney (trackerID, routeID, driverID, plateNumber, capacity) VALUES (3, 3, 3, 'PLT003', 8);
INSERT INTO jeepney (trackerID, routeID, driverID, plateNumber, capacity) VALUES (4, 4, 4, 'PLT004', 8);
INSERT INTO jeepney (trackerID, routeID, driverID, plateNumber, capacity) VALUES (5, 5, 5, 'PLT005', 8);
